### ISSUE TITLE
STEP file won't load in Solidworks 2017

### ISSUE THREAD

**Issue by Snowflake6** [stratux/ahrs#1]
More of an FYI, I guess.  Maybe try an IGES file?

**Comment by cyoung** [comment]
How does this look?


https://gist.github.com/cyoung/6ae15d9e0018bbb1b6fee67a096b1987

**Comment by Snowflake6** [comment]
Odd.  That won't load either.  Here's the import report, which seems to detect a lot of IGES entities but doesn't make any Solidworks entities with them.
`*****************************************************************
      SolidWorks Corporation - IGES Processor Status Report
*****************************************************************
=================================================================
General Information
=================================================================
Sending System Product I.D.  : AHRS
Receiving System Product I.D.: 
File Name                    : AHRS
Sending System               : unknown
Preprocessor Version         : unknown
File Creation Date           : 20170519.191253
Model Creation Date          : 
Units                        : MM
Model Space Scale            : 1
Author                       : unknown
Organization                 : unknown


=================================================================
Entity Processing Information
=================================================================


=================================================================
Precision analysis of IGES file:
=================================================================


=================================================================
Entity Summary
=================================================================
-----------------------------------------------------------------
Type Name                                         Count Converted
---- ----                                         ----- ---------
124  Transformation matrix                           12        12
126  Rational B-spline curve                       2502      2502
128  Rational B-spline surface                      877       877
141  Boundary                                        36        36
143  Bounded surface                                 36        36
186  Manifold Solid B-rep Object                      6         6
308  Subfigure definition                            22         7
314  Color definition                                 8         8
406  Property                                        63        63
408  Singular subfigure instance                     27        27
502  Vertex list                                      6         6
504  Edge entity                                      6         6
508  Loop entity                                    916       916
510  Face entity                                    841       841
514  Shell entity                                     6         6
_________________________________________________________________


=================================================================
Result Summary
=================================================================
SolidWorks Feature Type                Count
-----------------------                -----
Solid feature(s)                       0
Surface feature(s)                     0
Curve/Sketch feature(s)                0
--------------------------------------------
Start time: Friday, May 19, 2017 16:16:06
Finish time: Friday, May 19, 2017 16:16:09
Processing time: 0 days, 00 hours, 00 mins, 03 secs
`

**Comment by cyoung** [comment]
Looks like a file format/download issue - `git clone` if needed again in the future.
